# Docker Hub
#FROM library/nginx
# AWS ECR Pull Through Cache
FROM 182399679812.dkr.ecr.ap-northeast-1.amazonaws.com/docker-hub/library/nginx

COPY ./prod/nginx/default.conf /etc/nginx/conf.d/default.conf
