<?php

namespace App\Console\Commands;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

class RemoveModelCommand extends BaseCommand
{
    protected $signature = 'rm:model {name : Model name (StudlyCase)} {--yes : Force yes to all prompts}';
    protected $description = 'Remove an app model and files generated by m:model (test, factory, seeder, migrations).';

    public function handle(): int
    {
        /** @var Filesystem $files */
        $files = $this->laravel['files'];

        $rawName = Str::studly((string) $this->argument('name'));
        $modelClass = Str::endsWith($rawName, 'Model') ? Str::beforeLast($rawName, 'Model') : $rawName;
        $table = Str::snake(Str::pluralStudly($modelClass));

        $paths = [
            app_path("Models/{$modelClass}.php"),
            base_path("tests/Unit/Models/{$modelClass}ModelTest.php"),
            database_path("factories/{$modelClass}Factory.php"),
            database_path("seeders/{$modelClass}Seeder.php"),
        ];

        $migrationPattern = database_path("migrations/*_create_{$table}_table.php");
        $migrationPaths = glob($migrationPattern) ?: [];

        foreach ($paths as $path) {
            $this->deletePath($files, $path);
        }

        foreach ($migrationPaths as $migrationPath) {
            $this->deletePath($files, $migrationPath);
        }

        if ($migrationPaths === []) {
            $this->warn("No migration matched pattern: {$migrationPattern}");
        }

        return 0;
    }

    private function deletePath(Filesystem $files, string $path): void
    {
        if (! $files->exists($path)) {
            $this->warn("Not found: {$path}");
            return;
        }

        if (! $this->shouldDelete($path)) {
            $this->info("Skipped: {$path}");
            return;
        }

        $files->delete($path);
        $this->info("Deleted: {$path}");
    }

    private function shouldDelete(string $path): bool
    {
        if ($this->shouldForceYes()) {
            return true;
        }

        if ($this->shouldSkipQuestions() || ! $this->input->isInteractive()) {
            return false;
        }

        return $this->confirm("Delete {$path}?", false);
    }
}
